name: minio
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 3.5.0
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  buffer: ^1.1.0
  convert: ^3.0.0
  crypto: ^3.0.0
  http: ^1.1.1
  intl: ^0.17.0
  meta: ^1.3.0
  mime: ^1.0.0
  path: ^1.8.0
  xml: ^5.0.2


dev_dependencies:
  html: ^0.15.0
  test: ^1.16.8
  very_good_analysis: ^5.1.0
